apiVersion: apps/v1
kind: Deployment
metadata:
  name: absence-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: absence-app
  template:
    metadata:
      labels:
        app: absence-app
    spec:
      containers:
      - name: absence-app
        image: absence-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sqlite-storage
          mountPath: /var/www/data
      volumes:
      - name: sqlite-storage
        hostPath:
          path: /data/k8s-storage/db
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: absence-app-service
spec:
  selector:
    app: absence-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: absence-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: absence-app-service
            port:
              number: 80
